# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 787166150a64a933ba9d0ac0fc326470a590d755c5b6a07a2f81cdbb54443ace188231624ea3f5752d0f0f514c9abcbcd85830bb6bdc99b6721c61875eab544c

test:
  secret_key_base: 42f93c6783f276886409515e6ae873219fcdc144042b40519ddff923826a8e0978717756d4c7a3ea7548fed3614c1e86b698137493109880b7a846e7d1931f54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
